- deps.edn
- pom.xml
Not sure how much of the pom.xml needs to be checked in, but I don't know the tooling around deps.edn well enough to know how to specify the coordinates for the clojars artefact.
> Add deployment to deps.edn

- pom.xml
This is cleaned up to match how next.jdbc, expectations, and several other libs I maintain are configured.
> Fix #121 by updating SCM information in pom.xml

- .github/workflows/nvd_scanner.yml
- README.md
- nvd_check_helper_project/deps.edn
- nvd_check_helper_project/github_actions_config.json
- nvd_check_helper_project/suppressions.xml
Using nvd-clojure to scan for security issues in deps. Borrowed from the work that @slipset did for clj-yaml.
> ci: add vulnerability scanning

- CHANGES.md
Noticed some unreleased changes that were not described
> docs: fill in gaps in changelog

- deps.edn
To support testing against different versions of Clojure.
Contributes to #137
> dev: add deps.edn aliases for Clojure versions

- .github/workflows/tests.yml
- .gitignore
- bb.edn
- doc/02-developer-guide.adoc
add bb task
add to GitHub Action tests workflow (matching current CircleCI config) 
add to dev guide
Contributes to #137
> dev: eastwood love

- CHANGELOG.adoc
- deps.edn
- doc/02-developer-guide.adoc
- script/test_clj.clj
> tests: restore testing with old Clojure versions

- deps.edn
Because we love our little linter!
> maint: bump clj-kondo

- .github/workflows/nvd_scanner.yml
- bb.edn
- doc/02-developer-guide.adoc
- nvd_check_helper_project/local_config.json
> dev: support running vulnerability scan locally

- doc/03-maintainer-guide.adoc
My workflow was a bit forking nuts. Adjust docs.
> docs: maintainer guide tweak

- .github/workflows/nvd_scanner.yml
set-output is deprecated, move to new syntax
> ci: address github action deprecation warning

- doc/01-user-guide.adoc
> docs: make note of Clojure 1.12 add lib support

- .github/workflows/tests.yml
> ci: add JDK 20 to test matrix

- doc/01-user-guide.adoc
> docs: correct user guide deploy example

- bb.edn
- deps.edn
- doc/02-developer-guide.adoc
> dev: add outdated task and advice

- doc/01-user-guide.adoc
> docs: user-guide: typos

- nvd_check_helper_project/suppressions.xml
> Suppress false positive reported by nvd scan

- .github/workflows/tests.yml
> ci: update jdk test matrix

- .clj-kondo/taoensso/encore/config.edn
- .clj-kondo/taoensso/encore/taoensso/encore.clj
- bb.edn
- deps.edn
Of note: bump clojure 1.11 and 1.12 to current releases
> test maint: bump deps to current

- CHANGELOG.adoc
- deps.edn
- Review changelog
- Bump tools.build dep
> maint: prep for release

- .github/workflows/nvd_scanner.yml
- .github/workflows/shared-setup/action.yml
- deps.edn
- script/publish.clj
- src/test/clojure/cemerick/pomegranate/aether_test.clj
Of note, new kondo linter found a few redundant str calls. Cool! Fixed!
> test & ci: bump deps

- deps.edn
- nvd_check_helper_project/deps.edn
bump of dependency check should fix failing nvd-scan
> ci: bump deps

- deps.edn
Who can resist trying a new version of clj-kondo?
> dev: bump clj-kondo

- CHANGELOG.adoc
- deps.edn
> Override maven dep to address CVE-2025-48924

- bb.edn
- script/lint.clj
There is no longer a deps.edn in nvd subproject but there is now a bb.edn. And nvd subproject dir name changed.
Addendum for #225
> fix nvd change breakages
