pom.xml

Java 9 no longer has sun.misc.Launcher, which dynapath < 0.2.4 assumed
was always available.
This enables pomegranate to work under early access builds of Java 9.

Update to dynapath 0.2.4 to support Java 9

---

pom.xml

This version addresses two Java 9 related issues:
* 0.2.4 would fail under Java 9 if AOT'd
* the latest Java 9 build (9-ea+148) broke dynapath's reflection to make
URLClassLoader modifiable

Update to dynapath 0.2.5

---

.travis.yml
README.md
pom.xml
src/main/clojure/cemerick/pomegranate.clj
src/main/clojure/cemerick/pomegranate/aether.clj
src/test/clojure/cemerick/pomegranate/aether_test.clj
test-repo/demo/demo/1.0.0/demo-1.0.0.jar.asc.md5
test-repo/demo/demo/1.0.0/demo-1.0.0.jar.asc.sha1
test-repo/demo/demo/1.0.0/demo-1.0.0.pom.asc.md5
test-repo/demo/demo/1.0.0/demo-1.0.0.pom.asc.sha1

This builds on #80 but takes it a bit further.
* brings Maven up to 3.5.0, which wasn't released when the first PR was created
* drops support for OpenJDK6
* does not support non-TLS HTTP repositories out of the box
* adds a test for registering new wagons
* deletes a test for proxy support that assumed repo1.maven.org could be used as a proxy for repo1.maven.org
Note that item 3 above is technically a breaking change; however I would argue it is a bugfix for a critical security flaw. It's still possible to explicitly opt-in to non-TLS HTTP repositories if you don't care for security by calling `register-wagon-factory!` yourself.

Upgrade aether

---

src/main/clojure/cemerick/pomegranate/aether.clj

Prior to this commit, the `merge-versions-from-managed-coords` fn
was marked as private, because I didn't think it would need to be
called from outside of pomegranate.
However, it turned out to be a requirement to be able to call this
from leiningen in order to implement support for managed dependencies
in leiningen, and the function seems like it could be generally
useful for other cases, so this commit makes it public.
In the current leiningen code we are simply calling the private
function, so getting this merged and release is not a blocker for
anything, but it'd permit a desirable minor cleanup in the
corresponding leiningen code.

Make `merge-versions-from-managed-coords` fn public

---

src/main/clojure/cemerick/pomegranate/aether.clj

Hi!
I'd like to publish 'dependency' and 'make-repository' Aether-wrapping APIs as they are generally useful and they'd especially help me with https://github.com/circlespainter/lein-capsule.
Do you see any drawbacks?
TIA - Fabio

Publishing 'dependency' and 'make-repository' Aether-wrapping APIs as they are generally useful

---

src/main/clojure/cemerick/pomegranate/aether.clj
src/test/clojure/cemerick/pomegranate/aether_test.clj

This makes it so that `lein change repositories:private dissoc :passphrase` can work.

Allow repository names to be keywords or symbols or whatever.

---

src/test/clojure/cemerick/pomegranate/aether_test.clj

Unit tests are currently failing because Google’s Maven Central mirror,
which Pomegranate uses for testing mirrors, seems to have moved to a new
location. See
https://storage-download.googleapis.com/maven-central/index.html.
This change updates the URL, making the tests pass again. Thank you!

Update Google Maven Central mirror URL

---

src/main/clojure/cemerick/pomegranate/aether.clj
src/test/clojure/cemerick/pomegranate/aether_test.clj

I looked through @technomancy’s merged pull request #83, and found that
setting proxy authentication now always triggers an exception.
The reason is that `Proxy.setAuthentication` no longer exists –
authentication info must be passed to `Proxy` in the constructor. The
change here fixes this and also cleans up some small things (unused
binding, consistent arg name).
It is possible that this might fix technomancy/leiningen#2151 (just a
guess, I don’t have a proxy to test).

Fix exception thrown when setting proxy authentication

---

CHANGES.md
README.md

Readme and changelog mention still Aether, but the latest release updated Pomegrnate to use Maven-resolver (which replaces Aether): https://github.com/cemerick/pomegranate/pull/83/commits/c4e19981c53311e52f5a8060f34b6d3b69d458bd

Fix mentions of Aether to point to Maven-resolver

---

pom.xml

With the advent of restrictions on reflection in Java 9, anything that
loads dynapath will cause a warning to be printed to stdout complaining
about reflective access to `URLClassLoader`, even if no code tries to
modify a `URLClassLoader`:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by dynapath.defaults$fn__1516$fn__1517 (file:/Users/kanwei/.m2/repository/boot/pod/2.7.2/pod-2.7.2.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of dynapath.defaults$fn__1516$fn__1517
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
The only change in …

Update to dynapath 1.0.0

---

README.md

Using old "1.2.3" version leads to the "Could not obtain transporter
factory for http://build.clojure.org/snapshots" error.
See https://github.com/cemerick/pomegranate/issues/99

Use latest incanter version in the README example.

---

pom.xml

This will pick up a fix for CVE-2018-10237 in `com.google.guava`, and
bring the rest of the dependencies up-to-date as a bonus.

Pick up fix for CVE-2018-10237

---

src/main/clojure/cemerick/pomegranate/aether.clj
src/test/clojure/cemerick/pomegranate/aether_test.clj

The proposed change tweaks the session configuration, such that signature checksums (files ending in `.asc.sha1`) are downloaded as well. This fixes #113, and downstream technomancy/leiningen#2567.
Details: We are currently using the (default) legacy repository layout instance that intentionally does not download signature checksums. To use the repository layout where signature checksums _are_ downloaded, the named configuration property `aether.checksums.forSignature` must be enabled.
In my view, this is a change we will have to make. In addition, we should consider going back from the `:fail` checksum policy to `:warn`, since the `:fail` policy causes checksum verification of most artefacts (all of Clojure core) to fail – that is, undo #28. This is independent of the change proposed …

Also download signature checksums

---

deps.edn
pom.xml

Version 3.6.0 of Maven Resolver Provider, which was recently introduced (a788dec827511063ebdb9b8b44174841519d043b), contains transitive dependencies that conflict with each other. This breaks Pomegranate consumers like Leiningen. The conflicts are resolved in version 3.6.1 of this dependency.
The proposed change bumps Maven Resolver Provider to 3.6.1. It also adds four ‘used but undeclared’ Maven resolver dependencies that are directly used in Pomegranate, and so should be declared as dependencies. Finally, it pins the transitive dependency `org.apache.httpcomponents/httpcore`, again to prevent a version conflict.
I have verified that this fixes the breakage in the Leiningen build, so this fixes #115.

Fix dependency conflict after recent Maven resolver version bumps

---

src/main/clojure/cemerick/pomegranate.clj
src/main/clojure/cemerick/pomegranate/aether.clj

When using this dependency with `*warn-on-reflect*` set, it produces a number of reflection warnings. I've added some type hints to fix them (as well as some simple logic in `resolve-dependencies` to select between two types).
```
Compiling namespace cemerick.pomegranate
Reflection warning, cemerick/pomegranate/aether.clj:109:49 - reference to field getMessage on java.lang.Object can't be resolved.
Reflection warning, cemerick/pomegranate/aether.clj:109:49 - reference to field getMessage on java.lang.Object can't be resolved.
Reflection warning, cemerick/pomegranate/aether.clj:143:35 - call to method newLocalRepositoryManager on java.lang.Object can't be resolved (no such method).
Reflection warning, cemerick/pomegranate/aether.clj:170:5 - call to method setSnapshotPolicy can't be …
```

Type hint to remove reflection warnings

---

deps.edn

The motivation for this is to restore display of the reason phrase
returned from the server. Clojars relies on this to convey more
context to the user when a deploy fails. Displaying it was removed in
wagon-http 3.2.0, and restored in 3.3.4 due to user complaint.
This should help resolve https://github.com/clojars/clojars-web/issues/774
once this is released and lein is updated to use the new version of
pomegranate.
The changelog for 3.3.2 -> 3.3.4 is
https://issues.apache.org/jira/browse/WAGON-541?jql=project%20%3D%20WAGON%20AND%20fixVersion%20in%20(3.3.3%2C%203.3.4)
with WAGON-541 being the relevant issue covering the reason phrase
changes.

Update wagon libs from 3.3.2 -> 3.3.4

---

.circleci/config.yml
deps.edn
src/main/clojure/cemerick/pomegranate.clj
src/main/clojure/cemerick/pomegranate/aether.clj
src/test/clojure/cemerick/pomegranate/aether_test.clj
src/test/clojure/cemerick/pomegranate_test.clj

> Closes https://github.com/clj-commons/pomegranate/pull/124
Picks up https://github.com/clj-commons/pomegranate/pull/124 from @emlyn. It's generally a fine commit except for Clojure 1.7 compatibility, and for some further opportunity of addressing the remaining reflection warnings.
That is done in the two following commits.
And the last commit sets up Eastwood as a linter. Starting from 0.9, it lints for reflection warnings in a way that is suitable for CI. You can learn more about how it works / its rationale in https://github.com/jonase/eastwood#reflection

Address all reflection warnings

---

deps.edn
src/main/clojure/cemerick/pomegranate/aether.clj

If one passes `[]` as the `:repositories`, fetches would fail.
`[]` can be passed under contrived-enough circumstances, which is what happened to me (making me lose time).

Don't accept empty but truthy :repositories

---

CHANGES.md
deps.edn
nvd_check_helper_project/suppressions.xml
pom.xml
src/main/clojure/cemerick/pomegranate/aether.clj

Address vulnerabilities reported by nvd-clojure by bumping deps.
Suppress reported CVEs for jsch.agentproxy.usocket-nc. I think they are false positives. See note in nvd suppression config.
Adapt to option change in maven resolver.
Pomegranate, by default, generates checksums for .asc files. This is not the default for maven resolver.
The maven resolver options that control this behaviour changed in maven resolver v1.8. Option aether.checksums.forSignature was replaced with aether.checksums.omitChecksumsForExtensions.
Because I've noticed that pomegranate users have explicitly set the legacy system property in their code, I've decided to have pomegranate automatically upconvert the legacy option to the new option.
Bump min Clojure version from 1.3.0 to 1.4.0.
Pomegranate uses the Clojure …

Bump deps to address vulnerabilities

---

.circleci/config.yml
deps.edn
pom.xml

These deps are not included in pomegranate release jar.
Did not bother with the deprecated depstar it shall soon be replaced with tools.build.
Carried on with using HEAD sha of deps-deploy as per its recommended usage in its README.
Contributes to #134

maint: bump dev deps

---

deps.edn
pom.xml

As of this writing, I think this is the last stale dep of interest.
Does not seem terribly risky as last release was in late 2019 and might help with newer JDKs in some way?
Closes #134

bump: dynapath

---

.clj-kondo/babashka/fs/config.edn
.clj-kondo/config.edn
.clj-kondo/lread/status-line/config.edn
.clj-kondo/rewrite-clj/rewrite-clj/config.edn
.github/workflows/tests.yml
.gitignore
CHANGES.md
bb.edn
deps.edn
doc/02-developer-guide.adoc
script/lint.clj
src/main/clojure/cemerick/pomegranate.clj
src/main/clojure/cemerick/pomegranate/aether.clj
src/test/clojure/cemerick/pomegranate/aether_test.clj
src/test/clojure/cemerick/pomegranate_test.clj

Some clear clarity wins:
- Removed unused private vars
- Removed unused imported classes
Subjective:
- Unused destructured `:keys` and `:as` now are prefixed with underscore. This allows these items to still act as docs, but conveys that they are not used and more importantly not used on purpose.
- An if without else converted to when. This very clearly conveys intent: no we did not forget the else condition.
- Converted :use clojure.test to :require :refer
Pure subjective liberties (not clj-kondo findings):
- I noticed that some nses were being required and not aliased. To me this indicates the ns is being included for its side effects. An alias, to me, conveys it is being used by code.
Closes #139

dev: add clj-kondo linting

---

CHANGELOG.adoc
bb.edn
deps.edn
doc/02-developer-guide.adoc
script/lint.clj
script/test_clj.clj
src/main/clojure/cemerick/pomegranate.clj
src/test-isolated/clojure/cemerick/pomegranate_isolated_test.clj
src/test/clojure/cemerick/pomegranate/test_report.clj
src/test/clojure/cemerick/pomegranate_test.clj

Reviewed/updated pomegranate ns tests.
Added some sanity testing for adding to the classpath. Since these modify classpaths they are run separately under a new `:isolated` test suite.
Added a warning to `get-classpath` docstring about JDK9+ behaviour.
Minor test fix: help for the cognitect runner is now invoked with old runner so it does not barf on old versions of Clojure.
Test reporter now also includes JDK version in addition to Clojure version. This might seem excessive, but because these are important for Pomegranate, I like a super-in-my-face reminder of what environment I am testing against.
Minor fix to Pomegranate exception messages now show simple classloader class name, for example:
- previously: `java.lang.IllegalStateException: Could not find a suitable classloader to modify …

add some classpath tests, fix a minor bug

---

src/main/clojure/cemerick/pomegranate/aether.clj
src/test/clojure/cemerick/pomegranate/aether_test.clj

If we explicitly add a scope to the Dependency object of a managed dependency (as we were doing, forcing `compile` if not provided), the resolved transitive dependency will use the explicit scope from the managed dependency (i.e. always resolving to `compile`).
Fixes https://github.com/clj-commons/pomegranate/issues/125, by not forcing a default scope for managed dependencies. This way, the resolved version will be from the managed dependency, but the scope of the original dependency will be preserved.

Do not set default scope in managed dependencies

---

nvd_check_helper_project/deps.edn

Apparently 10.0.2 is a mandatory update.

ci: vulnerability scan: bump dependency check

---

bb.edn
deps.edn
script/publish.clj

Of note:
- clojure 1.12 beta2!
- bb `pubcheck` task can now run checks on unpushed branch

test & ci: bump deps, tweak pubcheck
